---
# tasks file for roles/base
  - name: Install Python 3
    apt:
      name: python3
      state: present

  - name: Install pip
    apt:
      name: python3-pip
      state: present

  - name: Install Jupyter Notebook
    pip:
      name: jupyter
      state: present
      executable: pip3  

  - name: Configure Jupyter Notebook
    command: jupyter notebook --generate-config
    become: true
    args:
      creates: ~/.jupyter/jupyter_notebook_config.py
    become_user: "{{ workshop_usr }}"

  - name: Set Jupyter Notebook password
    become: true
    command: >
      python3 -c "from jupyter_server.auth import passwd; print(passwd('{{ jupyter_pass }}'))"
    register: hashed_password
    become_user: "{{ workshop_usr }}"

  - name: Update Jupyter Notebook config file
    become: true  
    lineinfile:
      dest: ~/.jupyter/jupyter_notebook_config.py
      line: "c.NotebookApp.password = '{{ hashed_password.stdout }}'"
      state: present
    become_user: "{{ workshop_usr }}"

  - name: Allow Jupyter Notebook connections from all IP addresses
    become: true
    lineinfile:
      dest: ~/.jupyter/jupyter_notebook_config.py
      line: "c.NotebookApp.ip = '{{ local_ip }}'"
      state: present
    become_user: "{{ workshop_usr }}"

  - name: Start Jupyter Notebook service
    become: true
    command: jupyter notebook --port={{ jupyter_port }} --no-browser
    async: 2419200 ## four weeks
    poll: 0
    become_user: "{{ workshop_usr }}"
    args:
       chdir: "/home/{{ workshop_usr }}"


