---
# tasks file for roles/base
  - name: Install R and related packages
    apt:
      name: 
        - r-base
        - r-base-dev
      state: present

  - name: Download and install RStudio Server
    get_url:
      url: https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.06.2-561-amd64.deb
      dest: /tmp/rstudio-server.deb
  
  - name: Install RStudio Server
    apt:
      deb: /tmp/rstudio-server.deb
      state: present

  - name: Set RStudio Server port
    ansible.builtin.lineinfile:
      path: /etc/rstudio/rserver.conf
      regexp: '^www-port='  # Search for the existing www-port line
      line: 'www-port=8787'  # Replace with your desired port number
    notify: Restart RStudio Server

  - name: Enable and start RStudio Server service
    systemd:
      name: rstudio-server
      state: started
      enabled: yes

  